#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app.swagger_ui:
    path: /documentation
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

contactMessage_post:
    methods: POST
    path: /api/v1/contactMessage
    controller: App\Controller\ContactController::saveMessage

contactMessage_get:
    methods: GET
    path: /api/v1/contactMessage
    controller: App\Controller\ContactController::getMessages

contactMessage_getElastica:
    methods: GET
    path: /api/v1/contactMessage/elastica
    controller: App\Controller\ContactController::getMessagesElastica

contactMessage_getRedis:
    methods: GET
    path: /api/v1/contactMessage/redis
    controller: App\Controller\ContactController::getMessagesRedis

contactMessage_getRepositoryCache:
    methods: GET
    path: /api/v1/contactMessage/redis/cache
    controller: App\Controller\ContactController::getMessagesRedisCache

contactMessage_getMessagesCache:
    methods: GET
    path: /api/v1/contactMessage/cache
    controller: App\Controller\ContactController::getMessagesCache