version: '3'
services:
    postgresql:
        image: postgres
        container_name: h2h-db
        ports:
            - '5433:5432'
        environment:
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_NAME}        
        networks:
            vpcbr:
    php:
        build: 
          context: ../
          dockerfile: ./docker/php-fpm/Dockerfile
        image: h2h-php:latest
        container_name: h2h-php
        healthcheck:
            interval: 10s
            timeout: 3s
            retries: 3
            start_period: 30s
        ports:
            - '9002:9000'
        environment:
            - SYMFONY_APP_ENV=${APP_ENV}
            - SYMFONY_APP_SECRET=${APP_SECRET}
            - SYMFONY_DATABASE_URL=pgsql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
            - CORS_ALLOW_ORIGIN=${CORS_ALLOW_ORIGIN}
            - DATABASE_DRIVER=pdo_pgsql
            - DATABASE_HOST=${DATABASE_HOST}
            - DATABASE_PORT=${DATABASE_PORT}
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_USER=${DATABASE_USER}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        volumes:
            - ../app:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/log
            - /var/www/symfony/vendor # ignore vendor files
            - /var/www/symfony/var/cache # ignore cache files
        networks:
            vpcbr:
    nginx:
        build: 
            context: ../
            dockerfile: ./docker/nginx/Dockerfile
        image: h2h-nginx:latest
        container_name: h2h-nginx
        environment:
            - VIRTUAL_HOST=localhost
            - FPM_CONTAINER_NAME=php
        ports:
            - '8080:81'
        depends_on:
            - php
        volumes:
          - ./logs/nginx/:/var/log/nginx:cached
        networks:
            vpcbr:    
    supervisor:
        command: "/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"
        container_name: h2h-supervisor
        depends_on:
            - php
        image: h2h-php:latest
        networks:
            vpcbr:
        restart: always
        volumes:
            - ../app:/var/www/symfony
    rabbitmq:
        container_name: h2h-rabbitmq
        depends_on:
            - nginx
        image: rabbitmq:latest
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: pass
        networks:
            vpcbr:
        ports:
            - 15673:15672
        restart: always
        hostname: rabbitmq
        volumes:
            - "./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
            - "./data/rabbitmq:/var/lib/rabbitmq"
            - "./logs/rabbitmq:/var/log/rabbitmq"
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
        environment:
            discovery.type: "single-node"
            xpack.security.enabled: false
        ports:
            - "9200:9200"
        networks:
            vpcbr:
    mongo:
        image: mongo
        restart: always
        container_name: h2h-mongodb
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: "root"
            MONGO_INITDB_ROOT_PASSWORD: "password"
        networks:
            vpcbr:
    redis:
        image: redis
        container_name: h2h-redis
        command: redis-server --requirepass yourpassword
        ports:
            - "6379:6379"
        networks:
            vpcbr:
        volumes:
            - ./data/redis:/data/redis
networks:        
   vpcbr:
       driver: bridge
