fos_elastica:
    clients:
        default: { host: docker-elasticsearch-1, port: 9200 }
    indexes:
        contact_message:
            persistence:
                elastica_to_model_transformer:
                    ignore_missing: true
                driver: orm
                model: App\Entity\ContactMessage
                provider: ~
                finder: ~
                listener: ~
            properties:
                id: ~
                name: ~
                email: ~
                message: ~
                agreement: ~
                createdAt:
                    type: "datetime"