fos_elastica:
    clients:
        default: { host: h2h-elasticsearch, port: 9200, compression: true, logger: true }
    indexes:
        contact_message:
            persistence:
                elastica_to_model_transformer:
                    ignore_missing: true
                driver: orm
                model: App\Entity\ContactMessage
                provider: ~
                finder: ~
                listener: ~
            properties:
                id: 
                    type: integer
                name: ~
                email: ~
                message: ~
                agreement: ~
                createdAt:
                    type: "date"