framework:
    messenger:
        # reset services after consuming messages
        reset_on_message: true

        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            amqp_email:
                dsn: amqp://user:pass@h2h-rabbitmq:5672/%2f/email
                options:
                    auto_setup: true
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0
                failure_transport: failed_email
            failed_email: 
                dsn: amqp://user:pass@h2h-rabbitmq:5672/%2f/failed_email
                retry_strategy:
                    service: 'App\Service\FailedRetryStrategy'
        routing:
            # Route your messages to the transports
            'App\Message\Email': amqp_email
